[package]
name = "pyrand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
rand = { version = "0.8.5", optional = true }
num = { version = "0.4.1" }

[features]
default = ["rand"]
